networks:
    app-network:
        driver: bridge
        
services:
    php53:
        build: ./docker/php
        volumes:
            - ./:/var/www/html
        networks:
            - app-network
    php84:
        build: ./docker/php84
        volumes:
            - ./:/var/www/html
        networks:
            - app-network
    nginx:
        image: nginx
        ports:
            - "8001:80"
        networks:
            - app-network
        volumes:
            - ./:/var/www/html
            - ./docker/nginx/conf.d:/etc/nginx/conf.d
            - ./docker/nginx/log/nginx:/var/log/nginx
    database:
        image: 'mysql:5.7'
        platform: linux/amd64
        ports:
            - '${DB_PORT:-3308}:3306'
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
        volumes:
            - ./docker/data/database:/var/lib/mysql:rw
            - ./docker/mysql/my.cnf:/etc/mysql/my.cnf
        networks:
            - app-network
